#!/bin/bash

# Instructions for Cursor IDE
echo ""
echo "🎯 CURSOR IDE SETUP INSTRUCTIONS:"
echo "================================="
echo ""
echo "🔄 Ensure the MCP server is running locally on port 3000"
echo "npm run dev:run"
echo ""
echo "1. Open Cursor IDE Settings:"
echo "   - Click on the settings icon in the top right corner of the screen"
echo ""
echo "2. Click on 'Tools & MCP' in the left sidebar"
echo ""
echo "3. Click on 'New MCP Server'"
echo "   This will open the 'mcp.json' configuration file"
echo ""
echo "4. Add the following configuration to your mcp.json:"
echo ""
echo "{"
echo "  \"mcpServers\": {"
echo "    \"polydoc-database-docs\": {"
echo "      \"url\": \"http://localhost:3000/mcp\","
echo "      \"env\": {}"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "5. Save the mcp.json file"
echo ""
echo "6. Restart Cursor IDE completely"
echo ""
echo "7. Verify the setup:"
echo "   - Open Settings → Tools & MCP"
echo "   - You should see 'polydoc-database-docs' with '5 tools enabled'"
echo ""
echo "🛠️  Available tools after setup:"
echo "   • build-database-documentation (comprehensive analysis)"
echo "   • scan-database-files (quick scanning)"
echo "   • debug-workspace-info (show current workspace root directories and paths)"
echo "   • debug-client-capabilities (check what capabilities the MCP client supports)"
echo "   • set-workspace-root (manually set the workspace root directory)"
echo ""
echo "📋 Example usage:"
echo "   Ask Cursor: 'Use build-database-documentation to analyze my project at /path/to/project'"
echo ""
echo "🔄 If you need to restart Cursor, run: ./restart-cursor.sh"
echo ""
echo "✅ Setup complete! Follow the instructions above to configure Cursor."
