import { DatabaseTable } from '../../domain/models/databaseModels.js';

// TODO: The HTML documentation has not been updated in a while, it is not up to date with the Markdown documentation.
/**
 * Generate HTML documentation for database entities
 */
export function generateHTMLDocumentation(
  projectName: string,
  entities: DatabaseTable[],
  metrics: any,
  fileTree: string,
  fileAnalysis: any[],
  options: any
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${projectName} - Database Documentation</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; margin: 0; padding: 20px; background: #f8f9fa; }
        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
        h1 { color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }
        h2 { color: #34495e; margin-top: 30px; }
        h3 { color: #7f8c8d; }
        .metric { background: #ecf0f1; padding: 15px; margin: 10px 0; border-radius: 5px; }
        .entity { background: #fff; border: 1px solid #ddd; margin: 20px 0; border-radius: 5px; padding: 20px; }
        table { width: 100%; border-collapse: collapse; margin: 15px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background-color: #f8f9fa; font-weight: 600; }
        .file-tree { background: #f8f9fa; padding: 15px; border-radius: 5px; font-family: monospace; white-space: pre; }
        .status-success { color: #27ae60; }
        .status-error { color: #e74c3c; }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 ${projectName} - Database Documentation</h1>
        <p><strong>Generated on:</strong> ${new Date().toISOString()}</p>
        
        <h2>📈 Metrics Overview</h2>
        <div class="metric">
            <strong>Total Files:</strong> ${metrics.totalFiles} | 
            <strong>Entities:</strong> ${metrics.totalEntities} | 
            <strong>Relationships:</strong> ${metrics.relationships.total}
        </div>
        
        ${options.includeFileTree ? `
        <h2>🗂️ File Structure</h2>
        <div class="file-tree">${fileTree}</div>
        ` : ''}
        
        <h2>🗄️ Database Entities</h2>
        ${entities.map(entity => `
            <div class="entity">
                <h3>${entity.name} (${entity.referenceFiles.map(ref => ref.type).join(', ')})</h3>
                <div><strong>Reference Files:</strong><br>
                    ${entity.referenceFiles.map(ref => `<code>${ref.filePath}</code> (${ref.type})`).join('<br>')}
                </div>
                ${entity.fields.length > 0 ? `
                    <h4>Fields</h4>
                    <table>
                        <tr><th>Name</th><th>Type</th><th>Nullable</th><th>Primary Key</th></tr>
                        ${entity.fields.map(field => `
                            <tr>
                                <td>${field.name}</td>
                                <td><code>${field.type}</code></td>
                                <td>${field.nullable ? '✅' : '❌'}</td>
                                <td>${field.primaryKey ? '🔑' : '❌'}</td>
                            </tr>
                        `).join('')}
                    </table>
                ` : ''}
            </div>
        `).join('')}
        
        <hr>
        <p><em>Documentation generated by Polydoc MCP Server v1.0.0</em></p>
    </div>
</body>
</html>`;
}
